name: 'Read Linux verison'
on:
  workflow_dispatch: 
  
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
     - name: get-kernel-version
       run: |
         KERNEL_VERSION=$(uname -r)
         echo "HOST_KERNEL_VER=KERNEL_VERSION">>GITHUB_OUTPUT
     - name: Run Build Container
       uses: docker://debina:trixie
       with:
         args: |
            apt-get update
            apt-get -y install kmod fuse
            modprobe fuse
    container:
      options: "--privileged --device /dev/fuse -v /usr/lib/modules/${{ needs.get-kernel-version.output.HOST_KERNEL_VER }}:/lib/modules/${{ needs.get-kernel-version.output.HOST_KERNEL_VER }}:shared"
