name: 'Read Linux verison'
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Get kernel version
       run: |
         KERNEL_VERSION=$(uname -r)
         echo "HOST_KERNEL_VER=KERNEL_VERSION">>GITHUB_ENV
         echo "Kernel version ${{ env.HOST_KERNEL_VER }}"
     - name: Run Build Container
       uses: docker://debina:trixie
       with:
         args: |
            apt-get update
            apt-get -y install kmod fuse
            modprobe fuse
       env:
         HOST_KERNEL_VER: ${{ env.HOST_KERNEL_VER }}
    container:
      options: "--privileged --device /dev/fuse -v /usr/lib/modules/${{ env.HOST_KERNEL_VER }}:/lib/modules/${{ env.HOST_KERNEL_VER }}:shared"
